if (MSVC)
    find_program(CMAKE_C_COMPILER "clang-cl")
    find_program(CMAKE_CXX_COMPILER "clang-cl")
else()
    find_program(CMAKE_C_COMPILER "clang")
    find_program(CMAKE_CXX_COMPILER "clang++")
endif()